services:
  - type: web
    name: my-telegram-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./clicker.db
      - key: PORT
        sync: 10000
      - key: BOT_TOKEN
        sync: fromDashboard
